### ISSUE TITLE
TestExplorer VS拡張にむけての課題など

### ISSUE THREAD

**Issue by kekyo** [persimmon-projects/Persimmon#103]
# PersimmonのTestExplorer VS拡張の問題をしらべてます。
- 元にしているリポジトリ: pocketberserker/Persimmon.VisualStudio.TestExplorer.Prototype
- ここまででわかったことについて共有します
  - re-implブランチをもとにしてます。
  - 超ざっくりまとめたのでアレ
  - 何かsuggestがあれば、足してください
# MissingMethodExceptionの発生個所
- TestCollectorImpl.testObjectsのシーケンスで、最後のyield時に、Persimmon.Contextクラスのコンストラクタが認識できない
  - 予想: Contextクラスのコンストラクタ第二引数で、FSharpList<'T>のバージョン相違
  - 理由: 例外発生時の直前のデバッグログにて、FSharp.Coreのバージョン 4.3.0.0 がロードされている。しかし、既にテストライブラリのロードメッセージの直後に 4.3.1.0 がロードされており、サイドバイサイド実行が行われている可能性がある。また、テスト対象アセンブリのロードにAssemblyName.Create()から作られたAssemblyNameを使っているため、アセンブリローダーは暗黙に（CodeBaseによるパスベースの）読み取り専用コンテキストにロードされ、デフォルトコンテキストの定義と競合している可能性があります。
  - なお、検証中にバージョンの混乱を避けるために、すべてnet40以上を使用するように変更して再ビルドしてテストしました。
# Persimmonパッケージはどうなっていると良いかを考察しました
- Persimmon（と付随するアセンブリ）は、テスト対象がどのような環境で使用されるのかがわからないため、現状のPersimmon本体はnet20環境でビルドされている。
- Persimmon.Runnerは、XDocument・XElementに依存しているので、net35-Clientが最低条件となります。
- Persimmon.Consoleは、単体での実行アセンブリとなるので、可能な限り最新バージョンのランタイムで動作させる必要がある（Persimmon.Consoleの想定バージョンより新しいランタイムでビルドされたアセンブリをテスト出来なくなる）
  - しかし、新しすぎるバージョンを想定すると、そのランタイムが存在しない環境で動かせなくなるという問題があります。
- 厳密名署名が必須です（VSIXで必要→Persimmonでも必要）
  - こんなことが可能かどうかはわかりませんが、VSIXでPersimmonのアセンブリを一切参照しなければ、Persimmon側に署名は不要になります...
- NuGet化するなら、net20/net35/net40/net45ぐらいでアセンブリを個別にビルドし、NuGet内に配置したほうがいい？（PCLも含む？）
  - F#はShared project行けるのか？ 又はソースをリンク参照で単一化しておくか。
- 非同期テストに対応させるには、net40以降とPCLについては独立したTaskクラスの操作アセンブリを用意する必要があるかも？（MSpecはそのように実装していた）
# Persimmon.VisualStudio.TestExplorerはどうなっていると良いかを考察しました
- Visual Studioの動作想定バージョンをVS2012とした場合、テストエクスプローラーに直接依存するすべてのアセンブリは、net45以上でビルドされなければならない。
  - Persimmonでいうなら、net45以上という想定でよい。
- テスト対象アセンブリの実行と探索は、出来るだけ依存関係の少ない、独立したアセンブリとしてビルドしたほうがいい。今回の場合は、Persimmon.Runner.WrapperのTestCollectorImplはFSharp.Coreに依存しているために、ややこしい問題が発生したと考えられるので、AppDomainの生成と実行だけを行うシンプルなファサードに徹したアセンブリをC#で作るのがいいかも。
  - 参考: MSpecのコードを見ると、AppDomainの生成と実行は独立したアセンブリで実行させていた（Machine.Specifications.VSRunnerアセンブリ・AppDomainExecutorクラス/net45）。必要な情報をどうやってシリアル化可能な状態で渡せるかがカギで、PersimmonはTestCaseクラスと対象アセンブリ（元はAssemblyクラスだがこれはNGなのでAssemblyNameクラス）を引き渡す事が出来るだけでOK？
  -  （テスト結果がどう返却されるのかがまだわかっていない）

**Comment by pocketberserker** [comment]
調査ありがとうございます！

* net20/net35/net40/net45ぐらいでアセンブリを個別にビルド
  * おそらくソースをリンク参照で単一化する方式になると思います
* 厳密名署名
  * Persimmon側で対応した方が事故を減らせそうなので、こちらで対応に同意します
* net40以降とPCLについては独立したTaskクラスの操作アセンブリを用意する必要があるかも？
  * 必要そうですね
* TestCaseクラスと対象アセンブリ
  * TestObjectインターフェースと対象アセンブリかな、と思いました

**Comment by kekyo** [comment]
* マルチプラットフォームバージョンとPCLの対応は後回しでも良いかなと思ってます。
* TestObjectインターフェイスの件は再確認します。
  * 多分AppDomain超えで一番安全なのは、カスタム型（自分で定義した型）を使わずに、mscorlibとかで定義されている型（primitiveとかstringなど）だけで情報の引き渡しをする事だと思うので、それが満たせられるかどうかかなと。
  * カスタム型を使った時点で、型に対応するアセンブリをAppDomainにロードする必要が生じて、ロードされるコンテキストの相違で面倒なことになると言う流れです。
  * 更には、テスト対象のアセンブリも独自に（バージョンが何かわからない：特にマルチプラットフォームバージョンに対応させた場合）Persimmonのアセンブリをデフォルトコンテキストにロードすることになるので、余計にややこしい...

**Comment by pocketberserker** [comment]
すみません、TestObjectはインターフェースではなくabstract classでした…
https://github.com/persimmon-projects/Persimmon/blob/9b4d899b29e2a5f2971a96297b93ec3ca85796f8/src/Persimmon/Types.fs#L70

**Comment by bleis-tift** [comment]
@kekyo デバッグ実行は簡単には難しそうですか？デバッグ実行の実現に向けた問題として分かっている点があったら知りたいです。

**Comment by kekyo** [comment]
TestAdapterのデバッグと言う事であれば、今は:

* Persimmon本体をビルドしておく
* TestAdapterをビルドする。その際、TestRunnerライブラリはGACに登録するようにビルド後イベントに書く
* TestAdapterを実行（Isolation env）して、Persimmon.slnをロードし、Test Explorerを表示させる
* 表示されるときにメッセージダイアログを表示する（Win32 MessageBox API）ので、プロセスIDを見てアタッチ
* 後は普通にデバッグ

のような手順です。若干面倒で、ひょっとするとメッセージボックスじゃなくてDebugBreak API（だったかな？）の方がアタッチの手間が一つ削減できるかもしれません（昔やって上手くいかなかったので、それ以来ダイアログ表示でやってる）

**Comment by kekyo** [comment]
* メッセージダイアログはDEBUGビルドでだけ表示される

**Comment by kekyo** [comment]
Persimmon.slnにTestAdapterを入れれば、後ひと手間削減できるかな

**Comment by bleis-tift** [comment]
あ、TestAdapterのデバッグではなく、Test Explorerのデバッグ実行機能のことです。

**Comment by kekyo** [comment]
今ちょっと走らせてみました。何となく勝手に良しなにやってくれるように見えます

* 他の問題があってまだまともにデバッグは出来ないのですが、例外が発生するとテスト中に発生した例外としてVSが捕捉してます
* 例外の捕捉だけ見ると、普通にNUnitとかMSTestとかでデバッグ実行しているのと同じような感じです
* そういえばMSTestとかでテスト中にデバッガに落ちた場合でも、スタックトレースにはAppDomain超えの表示が出ていたので、同じプロセス内であれば何もしなくても良い？

**Comment by bleis-tift** [comment]
マジカルだ・・・

**Comment by bleis-tift** [comment]
残課題
* [ ] 値へのジャンプ
    * FCS使えば行けそう
* [ ] AppDomainのUnload問題
    * グローバルミューテックスで解決できそう？
* [ ] GAC問題
    * 最悪msiインストーラ

**Comment by pocketberserker** [comment]
close old issue
