### ISSUE TITLE
setup/teardown

### ISSUE THREAD

**Issue by bleis-tift** [persimmon-projects/Persimmon#14]
setup/teardownはテストに副作用を持ち込むため、実装するかどうかの議論が必要。

**Comment by pocketberserker** [comment]
必要かどうかの議論がもっと必要だと思うので、1.0.0での実装対象から外します。

**Comment by bleis-tift** [comment]
名前については、`setup`や`teardown`を踏襲するより、`testWithBefore`等の別の名前にしておきたい。
理由: `setup`, `teardown`と言いつつ、アサーション違反時の原因の調査を考えると、`teardown`で後処理をしてしまうよりも`setup`の最初でやった方がよく、`setup`という名前に反する。

**Comment by pocketberserker** [comment]
https://github.com/persimmon-projects/Persimmon/issues/105#issuecomment-195707929 で`try-finally`で代替する話になったので閉じます。
