### ISSUE TITLE
リッチなエラー出力を行う Assert

### ISSUE THREAD

**Issue by pocketberserker** [persimmon-projects/Persimmon#4]
Quote メソッドと、コードクォートを受け取り eval する Run メソッドを拡張メソッドとして別モジュールに用意し、 open することで power assert 的な出力にできないだろうか?

**Comment by bleis-tift** [comment]
https://gist.github.com/bleis-tift/2ada797f068a819d17de のような出力の場合、

```
difference:
  - List.[1].MergedColumns: expected 1 but 2
```

のように出るといいかもしれない。

## 処理概要
ある型Tどうしのequalityがfalseを返す場合、その構成要素のequalityを再帰的にチェックしていく。
プリミティブな型の比較でfalseを返した場合、そこまでのパスをdifferenceとして出力する。
Tどうしのequalityがtrueを返す場合は、differenceを出力しない。

### 上記エラーでの具体的なステップ
1. リスト全体を比較 -> falseなので構成要素のequalityのチェックに進む
    1. 構成要素はHeadとTail
    1. Headどうしを比較 -> trueなのでdifferenceは出力しない
    1. Tailどうしを比較 -> falseなので構成要素のequalityのチェックに進む
        1. 構成要素はHeadとTail
        1. Headどうしを比較 -> falseなので構成要素のequalityのチェックに進む
            1. 構成要素はRowとColumnとMergedRowsとMergedColumnとFormatとData
            1. Rowどうしを比較 -> trueなのでdifferenceは出力しない
            1. Columnどうしを比較 -> trueなのでdifferenceは出力しない
            1. MergedRowsどうしを比較 -> trueなのでdifferenceは出力しない
            1. MergedColumnsどうしを比較 -> falseかつプリミティブな型なので、いままでのパスをdifferenceとして出力
            1. Formatどうしを比較 -> trueなのでdifferenceは出力しない
            1. Dataどうしを比較 -> trueなのでdifferenceは出力しない
        1. Tailどうしを比較 -> trueなのでdifferenceは出力しない

## この方法の問題点
* コレクションの比較で先頭から比較していくと、データの抜けなどでずれていた時にdifferenceが分かりにくくなる可能性がある
    * コレクションの場合はdiffを取る？
* SetやMapなど、順序が意味を持たないものに適用できない
* 同じ比較を何度も行うことになり、無駄が多くテストの実行時間が延びる可能性がある
    * `static member Diff: Self * Self -> Diff list` のようなメソッドが定義されている場合はそれを使うことで高速化する余地を残す？

**Comment by pocketberserker** [comment]
initial implementation https://github.com/persimmon-projects/Persimmon.Assertion/tree/d38f4dc895693825e66175513a99cf5cf03396b9

**Comment by pocketberserker** [comment]
Pealse use https://github.com/persimmon-projects/Persimmon.MuscleAssert .
