### ISSUE TITLE
seq同士を比較したい

### ISSUE THREAD

**Issue by hafuu** [persimmon-projects/Persimmon#73]
```fsharp  
let ``seq equality`` = test {
    do! assertEquals (seq { 1.. 3 }) (seq { 1..3 })
  }
```

```
Assertion Violated: seq equality
1. Expect: seq [1; 2; 3]
   Actual: seq [1; 2; 3]
```

これが成功するようなassertが欲しいです。

**Comment by bleis-tift** [comment]
`assertSeqEquals`とかそんな？

**Comment by hafuu** [comment]
```assertSeqEquals```みたいなのです！
とりあえず自分で作って対応しました。

**Comment by pocketberserker** [comment]
https://fsprojects.github.io/Paket/github-dependencies.html#Gist と https://gist.github.com/Gab-km/240aee6f170cb75179a550c80546e5ff を使って、暫定的な実装を取得する方法もあります。

**Comment by bleis-tift** [comment]
mapしてtryFindをtryPickにしてみました。動作確認はしてません。 https://gist.github.com/bleis-tift/ae0937d95d40bdcc360475fcd3d8eecf

**Comment by Gab-km** [comment]
@bleis-tift 個人的に、こっちの方がスッキリしていて良いですね。ありがとうございます！！

**Comment by pocketberserker** [comment]
Pealse use https://github.com/persimmon-projects/Persimmon.MuscleAssert .
