### ISSUE TITLE
assert中に例外が発生するとテストが止まる

### ISSUE THREAD

**Issue by hafuu** [persimmon-projects/Persimmon#75]
```fsharp
let exceptionTest = test {
  let! e = trap { it (failwith "ex") }
  do! assertEquals (typeof<System.Exception>) (e.InnerException.GetType())
  do! assertEquals ("hoge") (e.Message)
}
```
実行結果
```
   FATAL ERROR: exceptionTest
   --------------------------- exceptions ----------------------------
   1. System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
```

ドキュメントの「はじめに」、で
```do! assertEquals "" (e.StackTrace.Substring(0, 5))```
という記述があって、actualの部分では関数やメソッド呼び出しをする記述が推奨されてるっぽいのに、例外が発生するとテストが止まってしまう。
メソッドや関数を呼び出せば例外が発生する可能性はあると思う。

**Comment by bleis-tift** [comment]
アサートの順番に依存関係があった場合に(絶対に失敗することがわかりきっている)不要なアサートが表示されてうざいので、FATALが一個でもあったら打ち切る、という方針なのです。
FailureとFATALの差にもなって、これはそのままの方がいいかなー、と思うんですけどどうでしょう？

**Comment by hafuu** [comment]
上げた例ではassertの継続が可能ですが、継続可能な例外かどうかの判断がつかないというので納得しました。
